In [3]:
import urllib.request
import zipfile
import pandas as pd
import os

url = "https://archive.ics.uci.edu/static/public/240/human+activity+recognition+using+smartphones.zip"
zip_filename = "har_dataset.zip"
extract_folder = "har_data"

# 1. Download the raw zip file from the server
print("1. Downloading raw zip file...")
urllib.request.urlretrieve(url, zip_filename)

# 2. Extract the contents into a new folder called 'har_data'
print("2. Extracting files...")
with zipfile.ZipFile(zip_filename, 'r') as zip_ref:
    zip_ref.extractall(extract_folder)

# 3. Load the data using Pandas
print("3. Loading sensor data into tables...")
# The researchers split the data into "train" (for learning) and "test" (for evaluating).
# We will load the training data first.
X_train_path = os.path.join(extract_folder, "UCI HAR Dataset", "train", "X_train.txt")
y_train_path = os.path.join(extract_folder, "UCI HAR Dataset", "train", "y_train.txt")

# We use sep='\s+' which is a Regular Expression telling Pandas: 
# "Treat ANY amount of whitespace as a column separator"
X = pd.read_csv(X_train_path, sep='\s+', header=None)
y = pd.read_csv(y_train_path, sep='\s+', header=None, names=['Activity_Label'])

# 4. Verify the shape
print(f"\nSuccess!")
print(f"Features (X) Shape: {X.shape}")
print(f"Targets (y) Shape: {y.shape}")

display(X.head())

1. Downloading raw zip file...
2. Extracting files...
3. Loading sensor data into tables...

Success!
Features (X) Shape: (7352, 561)
Targets (y) Shape: (7352, 1)

,0,1,2,3,4,5,6,7,8,9,...,551,552,553,554,555,556,557,558,559,560
0,0.288585,-0.020294,-0.132905,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,...,-0.074323,-0.298676,-0.710304,-0.112754,0.030400,-0.464761,-0.018446,-0.841247,0.179941,-0.058627
1,0.278419,-0.016411,-0.123520,-0.998245,-0.975300,-0.960322,-0.998807,-0.974914,-0.957686,-0.943068,...,0.158075,-0.595051,-0.861499,0.053477,-0.007435,-0.732626,0.703511,-0.844788,0.180289,-0.054317
2,0.279653,-0.019467,-0.113462,-0.995380,-0.967187,-0.978944,-0.996520,-0.963668,-0.977469,-0.938692,...,0.414503,-0.390748,-0.760104,-0.118559,0.177899,0.100699,0.808529,-0.848933,0.180637,-0.049118
3,0.279174,-0.026201,-0.123283,-0.996091,-0.983403,-0.990675,-0.997099,-0.982750,-0.989302,-0.938692,...,0.404573,-0.117290,-0.482845,-0.036788,-0.012892,0.640011,-0.485366,-0.848649,0.181935,-0.047663
4,0.276629,-0.016570,-0.115362,-0.998139,-0.980817,-0.990482,-0.998321,-0.979672,-0.990441,-0.942469,...,0.087753,-0.351471,-0.699205,0.123320,0.122542,0.693578,-0.615971,-0.847865,0.185151,-0.043892

In [4]:
import os

print("Searching for the missing files...")

# os.walk goes through the 'har_data' folder and all its sub-folders
for root, dirs, files in os.walk("har_data"):
    for file in files:
        # If the searchlight finds our specific files, print their exact location
        if file == "X_train.txt":
            print(f"Found X_train at: {os.path.join(root, file)}")
        elif file == "y_train.txt":
            print(f"Found y_train at: {os.path.join(root, file)}")

Searching for the missing files...
Found X_train at: har_data\UCI HAR Dataset\train\X_train.txt
Found y_train at: har_data\UCI HAR Dataset\train\y_train.txt

In [5]:
import os
print(os.listdir("har_data"))

['UCI HAR Dataset', 'UCI HAR Dataset.names', 'UCI HAR Dataset.zip', '__MACOSX']

In [6]:
import zipfile
import os
import pandas as pd

# 1. Define the path to the hidden inner zip file
inner_zip_path = os.path.join("har_data", "UCI HAR Dataset.zip")

# 2. Extract it right back into the har_data folder
print("1. Extracting the inner zip file...")
with zipfile.ZipFile(inner_zip_path, 'r') as zip_ref:
    zip_ref.extractall("har_data")

# 3. Now the folders actually exist! Let's map the paths.
X_train_path = os.path.join("har_data", "UCI HAR Dataset", "train", "X_train.txt")
y_train_path = os.path.join("har_data", "UCI HAR Dataset", "train", "y_train.txt")

# 4. Load the data using Pandas
print("2. Loading sensor data into tables...")
X = pd.read_csv(X_train_path, sep='\s+', header=None)
y = pd.read_csv(y_train_path, sep='\s+', header=None, names=['Activity_Label'])

# 5. Verify the shape
print(f"\nSuccess!")
print(f"Features (X) Shape: {X.shape}")
print(f"Targets (y) Shape: {y.shape}")

display(X.head())

1. Extracting the inner zip file...
2. Loading sensor data into tables...

Success!
Features (X) Shape: (7352, 561)
Targets (y) Shape: (7352, 1)

,0,1,2,3,4,5,6,7,8,9,...,551,552,553,554,555,556,557,558,559,560
0,0.288585,-0.020294,-0.132905,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,...,-0.074323,-0.298676,-0.710304,-0.112754,0.030400,-0.464761,-0.018446,-0.841247,0.179941,-0.058627
1,0.278419,-0.016411,-0.123520,-0.998245,-0.975300,-0.960322,-0.998807,-0.974914,-0.957686,-0.943068,...,0.158075,-0.595051,-0.861499,0.053477,-0.007435,-0.732626,0.703511,-0.844788,0.180289,-0.054317
2,0.279653,-0.019467,-0.113462,-0.995380,-0.967187,-0.978944,-0.996520,-0.963668,-0.977469,-0.938692,...,0.414503,-0.390748,-0.760104,-0.118559,0.177899,0.100699,0.808529,-0.848933,0.180637,-0.049118
3,0.279174,-0.026201,-0.123283,-0.996091,-0.983403,-0.990675,-0.997099,-0.982750,-0.989302,-0.938692,...,0.404573,-0.117290,-0.482845,-0.036788,-0.012892,0.640011,-0.485366,-0.848649,0.181935,-0.047663
4,0.276629,-0.016570,-0.115362,-0.998139,-0.980817,-0.990482,-0.998321,-0.979672,-0.990441,-0.942469,...,0.087753,-0.351471,-0.699205,0.123320,0.122542,0.693578,-0.615971,-0.847865,0.185151,-0.043892

In [10]:
display(X.head())

,0,1,2,3,4,5,6,7,8,9,...,551,552,553,554,555,556,557,558,559,560
0,0.288585,-0.020294,-0.132905,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,...,-0.074323,-0.298676,-0.710304,-0.112754,0.030400,-0.464761,-0.018446,-0.841247,0.179941,-0.058627
1,0.278419,-0.016411,-0.123520,-0.998245,-0.975300,-0.960322,-0.998807,-0.974914,-0.957686,-0.943068,...,0.158075,-0.595051,-0.861499,0.053477,-0.007435,-0.732626,0.703511,-0.844788,0.180289,-0.054317
2,0.279653,-0.019467,-0.113462,-0.995380,-0.967187,-0.978944,-0.996520,-0.963668,-0.977469,-0.938692,...,0.414503,-0.390748,-0.760104,-0.118559,0.177899,0.100699,0.808529,-0.848933,0.180637,-0.049118
3,0.279174,-0.026201,-0.123283,-0.996091,-0.983403,-0.990675,-0.997099,-0.982750,-0.989302,-0.938692,...,0.404573,-0.117290,-0.482845,-0.036788,-0.012892,0.640011,-0.485366,-0.848649,0.181935,-0.047663
4,0.276629,-0.016570,-0.115362,-0.998139,-0.980817,-0.990482,-0.998321,-0.979672,-0.990441,-0.942469,...,0.087753,-0.351471,-0.699205,0.123320,0.122542,0.693578,-0.615971,-0.847865,0.185151,-0.043892